version: 2.1

parameters:
  release_tag:
    description: "Name of release tag (-arm will be added)"
    default: ""
    type: string
  image_name:
    description: "Subdirectory of package"
    default: "fenics"
    type: string
  image_description:
    description: "Description of package"
    default: ""
    type: string
  prefix:
    type: string
    default: "ghcr.io/scientificcomputing/"

jobs:
  docker-build-arm:
    machine:
      image: ubuntu-2004:2022.04.1
    resource_class: arm.medium

    steps:
      - checkout
      - run:
          command: |
            if [ ! -z "${DOCKER_USERNAME}" ]; then
              echo ${DOCKER_PASSWORD} | docker login ghcr.io -u ${DOCKER_USERNAME} --password-stdin
            fi

      - run:
          name: set environment variables
          command: |
            echo 'export IMAGE="<< pipeline.parameters.prefix >><< pipeline.parameters.image_name >>:<< pipeline.parameters.release_tag >>"' >> "$BASH_ENV"
      - run:
          command: |
            docker buildx build \
              --platform linux/arm64 \
              --label org.opencontainers.image.title="<< pipeline.parameters.image_name >>" \
              --label org.opencontainers.image.description="<< pipeline.parameters.image_description >>" \
              --tag "arm-build" \
              "<< pipeline.parameters.image_name >>"

      - run:
          name: wait for amd64 manifest to be pushed
          command: |
            while true; do
              docker manifest inspect $IMAGE && break || sleep 10
            done

      - run:
          name: merge manifests to publish multi-arch build
          command: |
            docker manifest create "$IMAGE" --amend "$IMAGE" --amend arm-build
            docker manifest push "$IMAGE"

workflows:
  build-arm:
    when: << pipeline.parameters.release_tag >>
    jobs:
      - docker-build-arm
